### PR TITLE
add VarChangeDeprecationFix

### PR DESCRIPTION
**Pull request by aramunn**
aliases the NextFrame event to the deprecated VarChange_FrameCount event

### CODE REVIEW

**Comment by Zod-** [comment]
Hm I'm not sure if I want to support deprecated stuff with this addon.

**Comment by aramunn** [comment]
Oh ok. Yeah that's fine. I thought this addon covered the last thing they deprecated that broke everything, but it turns out that was a different one. The fix for them deprecating it is pretty easy if you're comfortable doing a find/replace all, but I was thinking some might not be and they'd prefer to just download another addon to fix all the old ones that broke. If anyone requests it I can throw a new one together pretty quick.

**Comment by Zod-** [comment]
Might be interesting to have an addon to cover the deprecated stuff tho. If you just make one for this single fix you will end up making one everytime instead of just letting people update it from curse. 
I was more aiming to fix bugs in their addons with this one so I don't think it really fits here.

**Comment by aramunn** [comment]
Yeah that makes sense. I'll close this pull request. And I definitely agree on the single updating addon instead of multiple. Starting one up and hooking it all together takes me way too long haha.

**Pull request closed without merging**
